name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo dnf install -y gcc git meson ninja-build libusb1-devel

    - name: Configure
      run: meson setup builddir

    - name: Build
      run: meson compile -C builddir

    - name: Test
      run: meson test -C builddir

    - name: Create distribution package
      run: meson dist -C builddir

    - name: Upload distribution package
      uses: actions/upload-artifact@v4
      with:
        name: adsp-ldr
        path: builddir/meson-dist/*.tar.xz
