name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y meson ninja-build libusb-1.0-0-dev

    - name: Configure
      run: meson setup builddir

    - name: Build
      run: meson compile -C builddir
