name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y libusb-1.0-0-dev
        pip install meson

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure
      run: meson setup builddir

    - name: Build
      run: meson compile -C builddir

    - name: Test
      run: meson test -C builddir

    - name: Create distribution package
      run: meson dist -C builddir

    - name: Upload distribution package
      uses: actions/upload-artifact@v4
      with:
        name: adsp-ldr
        path: builddir/meson-dist/*.tar.xz
